"""
Output layer: LLM generates a structured final research report from execution results.

Called at the end of ``workflow_demo.run_workflow`` before emitting ``run_done``.
"""

from __future__ import annotations

import json
import os
from typing import Any, cast

from dotenv import load_dotenv
from openai import OpenAI
from pydantic import BaseModel, ConfigDict, Field

from .state import AgentState
from .workspace import Workspace


class ReportSection(BaseModel):
    heading: str
    body: str = Field(description="Markdown-formatted content for this section")


class FinalReport(BaseModel):
    """Structured research report generated by the LLM at the end of a run."""

    model_config = ConfigDict(extra="forbid")

    title: str = Field(description="Concise report title")
    executive_summary: str = Field(description="2-4 sentence high-level summary of the entire run")
    sections: list[ReportSection] = Field(
        description="Ordered report sections: methodology, data, features, model, backtest, evaluation, etc."
    )
    key_findings: list[str] = Field(description="3-6 bullet-point key findings")
    recommendations: list[str] = Field(description="2-5 actionable next steps")
    limitations: list[str] = Field(description="Known limitations or caveats")
    conclusion: str = Field(description="Final 1-2 sentence conclusion")


def _openai_client() -> OpenAI:
    key = os.environ.get("OPENAI_API_KEY")
    if not key:
        raise RuntimeError("OPENAI_API_KEY is not set.")
    base = os.environ.get("OPENAI_BASE_URL")
    kwargs: dict[str, Any] = {"api_key": key}
    if base:
        kwargs["base_url"] = base.rstrip("/")
    return OpenAI(**kwargs)


def _build_context(state: AgentState, workspace: Workspace) -> str:
    """Assemble concise context for the report-writing LLM."""
    parts: list[str] = []

    parts.append(f"## Goal\n\n{state.goal}")

    if state.plan:
        parts.append(f"## Plan summary\n\n{state.plan.goal_summary}")
        subtask_lines = [
            f"  {s.id}. {s.title} (deps: {s.dependencies})"
            for s in state.plan.subtasks
        ]
        parts.append("## Subtasks\n\n" + "\n".join(subtask_lines))

    parts.append(f"## Run status: {state.status}")
    parts.append(f"## Completed subtasks: {len(state.completed_subtasks)}/{len(state.plan.subtasks) if state.plan else '?'}")

    exec_lines: list[str] = []
    for rec in state.execution_log:
        out_summary = ""
        if rec.output and isinstance(rec.output, dict):
            important_keys = {
                "source", "rows", "columns", "model", "train_r2", "test_r2",
                "test_rmse", "sharpe", "max_drawdown", "total_return",
                "annual_return", "win_rate", "verdict", "overall_rating",
                "summary", "strengths", "weaknesses", "next_steps",
                "stopped_reason", "num_rounds", "planned_features",
                "engineered_shape", "feature_plan", "deploy_ready",
            }
            filtered = {k: v for k, v in rec.output.items() if k in important_keys}
            if filtered:
                out_summary = json.dumps(filtered, ensure_ascii=False, default=str)[:600]
        exec_lines.append(
            f"  - subtask {rec.subtask_id} → {rec.tool_name} [{rec.status}]: "
            f"{rec.result_summary[:150]}"
            + (f"\n    output: {out_summary}" if out_summary else "")
        )
    parts.append("## Execution log\n\n" + "\n".join(exec_lines))

    artifacts = workspace.list_artifacts()
    if artifacts:
        art_lines = [
            f"  - {name}: {meta.get('kind', '?')} {meta.get('description', '')}"
            + (f" shape={meta['shape']}" if meta.get("shape") else "")
            for name, meta in artifacts.items()
        ]
        parts.append("## Workspace artifacts\n\n" + "\n".join(art_lines))

    for name in ("model_output", "backtest_results", "evaluation", "feature_plan"):
        if workspace.has(name):
            try:
                data = workspace.load_json(name)
                trimmed = json.dumps(data, ensure_ascii=False, default=str)[:2000]
                parts.append(f"## Artifact: {name}\n\n{trimmed}")
            except Exception:
                pass

    return "\n\n".join(parts)


def generate_report(
    state: AgentState,
    workspace: Workspace,
    *,
    model: str | None = None,
    client: OpenAI | None = None,
) -> dict[str, Any]:
    """
    Generate a structured final report from the run's state and workspace.

    Returns the report as a JSON-serialisable dict and saves it to workspace
    as ``final_report``.
    """
    load_dotenv()
    m = model or os.environ.get("OPENAI_SMALL_MODEL")
    if not m:
        raise RuntimeError("OPENAI_SMALL_MODEL is not set.")

    context = _build_context(state, workspace)

    system = (
        "You are a senior quantitative researcher writing the final report for an automated research run. "
        "Given the execution context (goal, plan, tool outputs, metrics, artifacts), produce a structured report. "
        "Be specific: reference actual numbers, tool names, and artifact names. "
        "Use concise, professional language. "
        "Write section bodies in Markdown (use **bold**, bullet lists, code spans for numbers). "
        "Sections should cover: methodology/pipeline, data, features/analysis, model performance, "
        "backtest results, and evaluation. Adapt sections to what actually happened — skip sections "
        "for steps that didn't produce meaningful results. "
        "If the run had issues (failed steps, empty features, stub tools), note them honestly."
    )

    cli = client or _openai_client()
    completion = cli.chat.completions.parse(
        model=m,
        messages=[
            {"role": "system", "content": system},
            {"role": "user", "content": context},
        ],
        response_format=FinalReport,
    )
    parsed = completion.choices[0].message.parsed
    if parsed is None:
        fallback = {
            "title": "Run Report",
            "executive_summary": f"Run completed with status: {state.status}",
            "sections": [],
            "key_findings": [],
            "recommendations": [],
            "limitations": ["Report generation failed — LLM returned no output."],
            "conclusion": f"Status: {state.status}",
        }
        workspace.save_json("final_report", fallback, description="Final research report (fallback)")
        return fallback

    report = cast(FinalReport, parsed)
    report_dict = json.loads(report.model_dump_json())

    workspace.save_json(
        "final_report",
        report_dict,
        description="Final research report generated by LLM",
    )
    return report_dict
