"""
Output layer: LLM generates a structured final research report from execution results.

Called at the end of ``workflow_demo.run_workflow`` before emitting ``run_done``.

Uses structured ``parse`` first, then ``json_object`` fallback, then a deterministic
summary if the API or model does not support structured outputs.
"""

from __future__ import annotations

import json
import os
from typing import Any, cast

from dotenv import load_dotenv
from openai import OpenAI
from pydantic import BaseModel, ConfigDict, Field

from .events import sanitize_for_json
from .state import AgentState
from .workspace import Workspace


class ReportSection(BaseModel):
    heading: str
    body: str = Field(description="Markdown-formatted content for this section")


class FinalReport(BaseModel):
    """Structured research report generated by the LLM at the end of a run."""

    model_config = ConfigDict(extra="forbid")

    title: str = Field(description="Concise report title")
    executive_summary: str = Field(description="2-4 sentence high-level summary of the entire run")
    sections: list[ReportSection] = Field(
        description="Ordered report sections: methodology, data, features, model, backtest, evaluation, etc."
    )
    key_findings: list[str] = Field(description="3-6 bullet-point key findings")
    recommendations: list[str] = Field(description="2-5 actionable next steps")
    limitations: list[str] = Field(description="Known limitations or caveats")
    conclusion: str = Field(description="Final 1-2 sentence conclusion")


_JSON_SCHEMA_HINT = """Respond with one JSON object only, with exactly these keys:
"title" (string), "executive_summary" (string),
"sections" (array of objects with "heading" and "body" strings),
"key_findings" (array of strings), "recommendations" (array of strings),
"limitations" (array of strings), "conclusion" (string)."""


def _openai_client() -> OpenAI:
    key = os.environ.get("OPENAI_API_KEY")
    if not key:
        raise RuntimeError("OPENAI_API_KEY is not set.")
    base = os.environ.get("OPENAI_BASE_URL")
    kwargs: dict[str, Any] = {"api_key": key}
    if base:
        kwargs["base_url"] = base.rstrip("/")
    return OpenAI(**kwargs)


def _build_context(state: AgentState, workspace: Workspace) -> str:
    """Assemble concise context for the report-writing LLM."""
    parts: list[str] = []

    parts.append(f"## Goal\n\n{state.goal}")

    if state.plan:
        parts.append(f"## Plan summary\n\n{state.plan.goal_summary}")
        subtask_lines = [
            f"  {s.id}. {s.title} (deps: {s.dependencies})"
            for s in state.plan.subtasks
        ]
        parts.append("## Subtasks\n\n" + "\n".join(subtask_lines))

    parts.append(f"## Run status: {state.status}")
    n_plan = len(state.plan.subtasks) if state.plan else 0
    parts.append(f"## Completed subtasks: {len(state.completed_subtasks)}/{n_plan}")

    exec_lines: list[str] = []
    for rec in state.execution_log:
        out_summary = ""
        if rec.output and isinstance(rec.output, dict):
            important_keys = {
                "source", "rows", "columns", "model", "train_r2", "test_r2",
                "test_rmse", "sharpe", "max_drawdown", "total_return",
                "annual_return", "win_rate", "verdict", "overall_rating",
                "summary", "strengths", "weaknesses", "next_steps",
                "stopped_reason", "num_rounds", "planned_features",
                "engineered_shape", "feature_plan", "deploy_ready",
            }
            filtered = {k: v for k, v in rec.output.items() if k in important_keys}
            if filtered:
                out_summary = json.dumps(filtered, ensure_ascii=False, default=str)[:600]
        exec_lines.append(
            f"  - subtask {rec.subtask_id} → {rec.tool_name} [{rec.status}]: "
            f"{rec.result_summary[:150]}"
            + (f"\n    output: {out_summary}" if out_summary else "")
        )
    parts.append("## Execution log\n\n" + "\n".join(exec_lines))

    artifacts = workspace.list_artifacts()
    if artifacts:
        art_lines = [
            f"  - {name}: {meta.get('kind', '?')} {meta.get('description', '')}"
            + (f" shape={meta['shape']}" if meta.get("shape") else "")
            for name, meta in artifacts.items()
        ]
        parts.append("## Workspace artifacts\n\n" + "\n".join(art_lines))

    for name in ("model_output", "backtest_results", "evaluation", "feature_plan"):
        if workspace.has(name):
            try:
                data = workspace.load_json(name)
                trimmed = json.dumps(data, ensure_ascii=False, default=str)[:2000]
                parts.append(f"## Artifact: {name}\n\n{trimmed}")
            except Exception:
                pass

    return "\n\n".join(parts)


def build_fallback_report(
    state: AgentState,
    workspace: Workspace,
    *,
    error: str | None = None,
) -> dict[str, Any]:
    """Deterministic report when LLM calls fail; always JSON-serialisable."""
    limitations: list[str] = []
    if error:
        limitations.append(f"LLM report generation failed: {error}")
    limitations.append("This summary was assembled without a fresh LLM call.")

    summary_intro = state.plan.goal_summary if state.plan else state.goal
    lines = [
        f"- Subtask {rec.subtask_id}: **{rec.tool_name}** — {rec.status}\n  {rec.result_summary[:200]}"
        for rec in state.execution_log
    ]
    body = "\n".join(lines) if lines else "_No execution records._"

    n_err = sum(1 for r in state.execution_log if r.status == "error")
    findings = [
        f"Run status: **{state.status}**",
        f"Tools invoked: {len(state.execution_log)} step(s)" + (f", **{n_err}** error(s)" if n_err else ""),
    ]
    arts = list(workspace.list_artifacts().keys())
    if arts:
        findings.append(f"Workspace artifacts: {', '.join(arts[:12])}" + (" …" if len(arts) > 12 else ""))

    return sanitize_for_json(
        {
            "title": "Research run summary",
            "executive_summary": summary_intro[:800] if summary_intro else state.goal[:800],
            "sections": [{"heading": "Execution pipeline", "body": body}],
            "key_findings": findings,
            "recommendations": [
                "Inspect the log and workspace artifacts for full numeric results.",
                "If reports are often missing, confirm `OPENAI_SMALL_MODEL` supports JSON or structured output.",
            ],
            "limitations": limitations,
            "conclusion": f"The workflow finished with status `{state.status}`.",
        }
    )


def _report_to_markdown(report: dict[str, Any]) -> str:
    """Convert a structured report dict into a readable Markdown document."""
    lines: list[str] = []
    title = report.get("title", "Research Report")
    lines.append(f"# {title}\n")

    summary = report.get("executive_summary", "")
    if summary:
        lines.append(f"## Executive Summary\n\n{summary}\n")

    for section in report.get("sections") or []:
        heading = section.get("heading", "Section")
        body = section.get("body", "")
        lines.append(f"## {heading}\n\n{body}\n")

    findings = report.get("key_findings") or []
    if findings:
        lines.append("## Key Findings\n")
        for f in findings:
            lines.append(f"- {f}")
        lines.append("")

    recs = report.get("recommendations") or []
    if recs:
        lines.append("## Recommendations\n")
        for r in recs:
            lines.append(f"- {r}")
        lines.append("")

    limits = report.get("limitations") or []
    if limits:
        lines.append("## Limitations\n")
        for l in limits:
            lines.append(f"- {l}")
        lines.append("")

    conclusion = report.get("conclusion", "")
    if conclusion:
        lines.append(f"## Conclusion\n\n{conclusion}\n")

    return "\n".join(lines)


def _persist_and_return(workspace: Workspace, report_dict: dict[str, Any]) -> dict[str, Any]:
    safe = sanitize_for_json(report_dict)
    try:
        workspace.save_json(
            "final_report",
            safe,
            description="Final research report",
        )
    except OSError:
        pass

    try:
        md_content = _report_to_markdown(safe)
        md_path = workspace.root / "report.md"
        md_path.write_text(md_content, encoding="utf-8")
        safe["report_md_path"] = str(md_path)
    except OSError:
        pass

    return safe


def generate_report(
    state: AgentState,
    workspace: Workspace,
    *,
    model: str | None = None,
    client: OpenAI | None = None,
) -> dict[str, Any]:
    """
    Generate a structured final report from the run's state and workspace.

    Saves ``final_report.json`` to the workspace. Always returns a dict (never raises).
    """
    load_dotenv()
    m = model or os.environ.get("OPENAI_SMALL_MODEL")
    if not m:
        return _persist_and_return(
            workspace,
            build_fallback_report(state, workspace, error="OPENAI_SMALL_MODEL is not set."),
        )

    if not os.environ.get("OPENAI_API_KEY"):
        return _persist_and_return(
            workspace,
            build_fallback_report(state, workspace, error="OPENAI_API_KEY is not set."),
        )

    try:
        context = _build_context(state, workspace)
    except Exception as exc:  # noqa: BLE001
        return _persist_and_return(
            workspace,
            build_fallback_report(state, workspace, error=f"Context build failed: {exc}"),
        )

    system = (
        "You are a senior quantitative researcher writing the final report for an automated research run. "
        "Given the execution context (goal, plan, tool outputs, metrics, artifacts), produce a structured report. "
        "Be specific: reference actual numbers, tool names, and artifact names. "
        "Use concise, professional language. "
        "Write section bodies in Markdown (use **bold**, bullet lists, code spans for numbers). "
        "Sections should cover: methodology/pipeline, data, features/analysis, model performance, "
        "backtest results, and evaluation. Adapt sections to what actually happened — skip sections "
        "for steps that didn't produce meaningful results. "
        "If the run had issues (failed steps, empty features, stubs), note them honestly."
    )

    failures: list[str] = []

    try:
        cli = client or _openai_client()
    except Exception as exc:  # noqa: BLE001
        return _persist_and_return(
            workspace,
            build_fallback_report(state, workspace, error=str(exc)),
        )

    # 1) Preferred: native structured parse
    try:
        completion = cli.chat.completions.parse(
            model=m,
            messages=[
                {"role": "system", "content": system},
                {"role": "user", "content": context},
            ],
            response_format=FinalReport,
        )
        parsed = completion.choices[0].message.parsed
        if parsed is not None:
            report = cast(FinalReport, parsed)
            return _persist_and_return(workspace, json.loads(report.model_dump_json()))
    except Exception as exc:  # noqa: BLE001
        failures.append(f"structured parse: {exc}")

    # 2) Fallback: json_object + Pydantic validation
    try:
        r = cli.chat.completions.create(
            model=m,
            messages=[
                {"role": "system", "content": system + "\n\n" + _JSON_SCHEMA_HINT},
                {"role": "user", "content": context},
            ],
            response_format={"type": "json_object"},
        )
        raw = (r.choices[0].message.content or "").strip()
        if not raw:
            raise RuntimeError("empty model content")
        obj = json.loads(raw)
        validated = FinalReport.model_validate(obj)
        return _persist_and_return(workspace, json.loads(validated.model_dump_json()))
    except Exception as exc:  # noqa: BLE001
        failures.append(f"json_object: {exc}")

    # 3) Last resort: template summary (+ optional partial parse content in limitations)
    fb = build_fallback_report(state, workspace, error="; ".join(failures))
    return _persist_and_return(workspace, fb)
